name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # --- 生成白天模式图片 ---
      - name: Light mode
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: cchengoran525
          filename: metrics.light.svg
          config_theme: github-light
          config_timezone: Asia/Shanghai
          base: header
          # 模块 1：语言详情（含字节大小和百分比）
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          # 模块 2：Issue 和 PR 的详细状态追踪
          plugin_followup: yes
          plugin_followup_sections: user # 专注于你个人的 PR 和 Issue 状态
          committer_branch: output  # 关键：把图片存到 output 分支

      # --- 生成黑夜模式图片 ---
      - name: Dark mode
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: cchengoran525
          filename: metrics.dark.svg
          config_theme: github-dark
          config_timezone: Asia/Shanghai
          base: header
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_sections: user
          committer_branch: output  # 关键：把图片存到 output 分支
